import { isPreview, previewFetch } from "../workbench/preview";
// Session id is generated by the server and echoed back via X-Session-Id.
// We persist it in localStorage so a refresh keeps the same conversation.

const storageKey = () =>
  isPreview() ? "cothinker.preview.session-id" : "cothinker.session-id";
export const SESSION_HEADER = "X-Session-Id";

export function getSessionId() {
  try {
    return localStorage.getItem(storageKey()) || "";
  } catch {
    return "";
  }
}

export function setSessionId(id) {
  if (!id) return;
  try {
    localStorage.setItem(storageKey(), id);
  } catch {
    // ignore (private mode etc.)
  }
}

export function clearSessionId() {
  try {
    localStorage.removeItem(storageKey());
  } catch {
    // ignore
  }
}

// Drop-in replacement for fetch that injects X-Session-Id and persists
// any session id the server returns. Exposes the same Response so callers
// can stream the body as usual.
export async function sessionedFetch(input, init = {}) {
  const headers = new Headers(init.headers || {});
  const id = getSessionId();
  if (id) headers.set(SESSION_HEADER, id);

  const response = await (isPreview() ? previewFetch : fetch)(input, {
    ...init,
    headers,
  });

  const returned = response.headers.get(SESSION_HEADER);
  if (returned && getSessionId() === id) setSessionId(returned);

  return response;
}
